### ISSUE TITLE
Can't able to create delta table in Hive 2.3.8 - Getting Execution Error from org.apache.hadoop.hive.ql.exec.DDLTask. org.json4s.jackson.JsonMethods$.parse$...

### ISSUE THREAD

**Issue by SenthilNayagan** [delta-io/connectors#73] opened 2021-01-20 17:48 UTC
**My environment:**
HDP: 3.1.4
Ambari: Version 2.7.4
Hive: 2.3.8 (Installed as a standalone one)
Spark: 3.0.1 (Pre-built for Hadoop 2.7)

**Step 1:**
In my Hive 2, I have added the following properties in **hive-site.xml**:
```
<property>
  <name>hive.input.format</name>
  <value>io.delta.hive.HiveInputFormat</value>
</property>
<property>
  <name>hive.tez.input.format</name>
  <value>io.delta.hive.HiveInputFormat</value>
</property>
```

**Step 2:**
Created a simple delta data using Apach Spark (pyspark) as shown below:
```
data = spark.range(0, 5)
data.write.format("delta").save("/delta/table/path")
```

**Step 3:**
In my Hive 2 CLI, I have added Hive connector uber jar using the below statement:

`ADD JAR <path-to-jar>; 
`

**Step 4:**
In Hive 2 CLI, I tried creating an external delta table as shown below:
```
CREATE EXTERNAL TABLE deltaTable(col1 INT, col2 STRING)
STORED BY 'io.delta.hive.DeltaStorageHandler'
LOCATION '/delta/table/path'
```
**Note:** Location is a HDFS path where I store the delta data. Hence, I used **hdfs://** as my scheme. 

**I am not able to create a delta table in Hive and I am getting the below error:**
  
`**FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.DDLTask. org.json4s.jackson.JsonMethods$.parse$default$3()Z**`

Greatly appreciate if anyone could help in this regard. Thanks!

**Comment by zsxwing** [comment] 2021-01-21 01:33
Could you check what's the josn4s version in your environment? Looks a binary incompatibility issue of json4s

**Comment by zsxwing** [comment] 2021-09-17 16:30
Closing this as a duplicate of #137.

**Closed by zsxwing** 2021-09-17 16:30 UTC
Labels: need author feedback
