### ISSUE TITLE
Dependent jackson-module-scala_2.12 version 2.6.7.1,  lower version

### ISSUE THREAD

**Issue by melin** [delta-io/connectors#114] opened 2021-08-16 09:52 UTC
Dependent jackson-module-scala_2.12 version 2.6.7.1, lower version
<dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-scala_2.12</artifactId>
            <version>2.12.4</version>
        </dependency>

**Comment by zsxwing** [comment] 2021-09-17 16:29
Closing this as a duplicate of #137.

**Closed by zsxwing** 2021-09-17 16:29 UTC
